#!/bin/bash
echo "What is the new version?(example: 0.0.1)"
read VERSION
echo "Echo pushing new version to Github: $VERSION"

git tag v$VERSION
git push origin/main v$VERSION

echo "Updating go reference"
GOPROXY=proxy.golang.org go list -m github.com/idevelopthings/surrealdb.go.unofficial@v$VERSION

echo "Done!"
